# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT

env:
  CIRRUS_CLONE_DEPTH: 1
  CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=DEBUG -DCARES_STATIC=ON -DCARES_STATIC_PIC=ON -G Ninja"
  CMAKE_TEST_FLAGS: "-DCARES_BUILD_TESTS=ON"

task:
  matrix:
    - name: "Alpine amd64"
      env:
        DIST: "ALPINE"
        LC_ALL: "C"
        SCAN_BUILD: "scan-build"
        MAKE: "make"
        BUILD_ASAN: "yes"
        BUILD_UBSAN: "yes"
        BUILD_VALGRIND: "yes"
        BUILD_ANALYZE: "yes"
        TEST_SYMBOL_VISIBILITY: "yes"
      container:
        image: alpine:latest
    - name: "Ubuntu OLD amd64"
      env:
        DIST: "UBUNTU"
        LC_ALL: "C"
        MAKE: "make"
      container:
        image: ubuntu:20.04
    - name: "Debian arm64"
      env:
        DIST: "DEBIAN-ARM"
        LC_ALL: "C"
        SCAN_BUILD: "scan-build"
        MAKE: "make"
# For whatever reason, ASAN and UBSAN are likely to result in compiler
# termination on debian arm64.  I can't tell if this is really a crash
# or something like the OOM killer:
#    /usr/bin/c++ -DHAVE_CONFIG_H=1 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -I/tmp/cirrus-ci-build/cmakebld/test -I/tmp/cirrus-ci-build/cmakebld -I/tmp/cirrus-ci-build/cmakebld/src/lib -I/tmp/cirrus-ci-build -I/tmp/cirrus-ci-build/src/lib -I/tmp/cirrus-ci-build/include -fsanitize=address -Wall -Wextra -Wcast-align -Wformat-security -Wmissing-declarations -Wmissing-format-attribute -Wpacked-bitfield-compat -Wredundant-decls -Wvla -Wno-unused-parameter -Wconversion -Wfloat-equal -Wsign-conversion -fdiagnostics-color=always -g -fno-omit-frame-pointer -O0 -DGTEST_HAS_PTHREAD=1 -std=c++14 -MD -MT test/CMakeFiles/arestest.dir/ares-test-parse-a.cc.o -MF test/CMakeFiles/arestest.dir/ares-test-parse-a.cc.o.d -o test/CMakeFiles/arestest.dir/ares-test-parse-a.cc.o -c /tmp/cirrus-ci-build/test/ares-test-parse-a.cc
#    c++: fatal error: Killed signal terminated program cc1plus
# Skip for now on arm.
        BUILD_ASAN: "no"
        BUILD_UBSAN: "no"
        BUILD_ANALYZE: "yes"
      arm_container:
        image: debian:latest
    - name: "FreeBSD amd64"
      env:
        DIST: "FREEBSD"
        SCAN_BUILD: "scan-build"
        MAKE: "gmake"
        BUILD_ANALYZE: "yes"
        TEST_SYMBOL_VISIBILITY: "yes"
      freebsd_instance:
        image_family: freebsd-13-3
    - name: "iOS"
      env:
        DIST: "iOS"
        MAKE: "make"
        CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=DEBUG -DCARES_STATIC=ON -DCARES_STATIC_PIC=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.0 -DCMAKE_OSX_ARCHITECTURES=armv7;armv7s;arm64 -G Ninja"
        CMAKE_TEST_FLAGS: "-DCARES_BUILD_TESTS=OFF"
        CFLAGS: "-arch armv7 -arch armv7s -arch arm64 -miphoneos-version-min=10.0"
        CONFIG_OPTS: "--host=arm-apple-darwin10 --disable-tests"
      macos_instance:
        image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  matrix:
    - name: "CMAKE"
      env:
        BUILD_TYPE: "cmake"
    - name: "AUTOTOOLS"
      env:
        BUILD_TYPE: "autotools"
    - name: "ASAN"
      # ASAN on Linux automatically includes Leak Sanitizer
      # FreeBSD just hangs trying to run tests, think it may be trying to run leak sanitizer
      only_if: $BUILD_ASAN == 'yes'
      env:
        BUILD_TYPE: "asan"
        CC: "clang"
        CONFIG_OPTS: "--enable-debug"
        CFLAGS: "-fsanitize=address"
        CXXFLAGS: "-fsanitize=address"
        LDFLAGS: "-fsanitize=address"
    - name: "UBSAN"
      # FreeBSD just hangs trying to run tests, think it may be trying to run leak sanitizer
      only_if: $BUILD_UBSAN == 'yes'
      env:
        BUILD_TYPE: "ubsan"
        CC: "clang"
        CONFIG_OPTS: "--enable-debug"
        CFLAGS: "-fsanitize=undefined -fno-sanitize-recover"
        CXXFLAGS: "-fsanitize=undefined -fno-sanitize-recover"
        LDFLAGS: "-fsanitize=undefined"
    - name: "ANALYZE"
      only_if: $BUILD_ANALYZE == 'yes'
      env:
        BUILD_TYPE: "analyze"
        CC: "clang"
        SCAN_WRAP: "${SCAN_BUILD} -v --status-bugs"
        CONFIG_OPTS: "--enable-debug --disable-tests"
        CMAKE_TEST_FLAGS: "-DCARES_BUILD_TESTS=OFF"
    - name: "VALGRIND"
      # FreeBSD just hangs trying to run tests, think it may be trying to run leak sanitizer
      only_if: $BUILD_VALGRIND == 'yes'
      env:
        BUILD_TYPE: "valgrind"
        TEST_WRAP: "valgrind --leak-check=full"
        TEST_FILTER: "-4 --gtest_filter=-*Container*:-*LiveSearchANY*"
    - name: "COVERAGE"
      only_if: $BUILD_COVERAGE == 'yes'
      env:
        BUILD_TYPE: "coverage"
        CI_NAME: "cirrus-ci"
        CI_BUILD_NUMBER: "${CIRRUS_TASK_ID}"
        CI_BUILD_URL: "https://cirrus-ci.com/task/${CIRRUS_TASK_ID}"
        CI_BRANCH: "${CIRRUS_BRANCH}"
        CI_PULL_REQUEST: "${CIRRUS_PR}"
        COVERALLS_REPO_TOKEN: "ENCRYPTED[a46bc6ca908e9e74f102c686cde67cae21d3e792dff46a60e860d1179d9349e8eb5a529132d0effefebdb0dbc3f95810]"
        CONFIG_OPTS: "--enable-debug --disable-shared --enable-code-coverage --enable-tests"

  install_script:
    - |
      case "${DIST}" in
        ALPINE)
          apk add bash cmake samurai gtest-dev autoconf autoconf-archive automake libtool pkgconf make
          case "${BUILD_TYPE}" in
            asan|lsan|ubsan)
              apk add clang17 compiler-rt
              ;;
            analyze)
              apk add clang17 clang17-analyzer compiler-rt
              ;;
            valgrind)
              apk add gcc g++ valgrind
              ;;
            *)
              apk add gcc g++
              ;;
          esac
          ;;
        UBUNTU|DEBIAN*)
          export DEBIAN_FRONTEND=noninteractive && \
          apt-get update && \
          apt-get install -y cmake ninja-build autoconf automake libtool g++ libgmock-dev pkg-config
          case "${BUILD_TYPE}" in
            asan|lsan|ubsan)
              apt-get install -yq clang
              ;;
            analyze)
              apt-get install -yq clang clang-tools
              ;;
            valgrind)
              apt-get install -yq valgrind
              ;;
            coverage)
              apt-get install -yq lcov git pip
              pip3 install --break-system-packages --user cpp-coveralls
              ;;
          esac
          ;;
        FREEBSD)
          # pkg upgrade -y && \
          pkg install -y bash cmake ninja googletest pkgconf
          ln -sf /usr/local/bin/bash /bin/bash
          case "${BUILD_TYPE}" in
            asan|analyze|ubsan|lsan)
              pkg install -y llvm autoconf automake libtool gmake
              ;;
            autotools)
              pkg install -y autoconf automake libtool gmake
              ;;
          esac
          ;;
        MACOS|iOS)
          brew update
          brew install ninja cmake googletest
          case "${BUILD_TYPE}" in
            asan|ubsan|lsan|analyze)
              brew install llvm autoconf automake libtool make ninja
              ;;
            autotools)
              brew install autoconf automake libtool make
              ;;
          esac
          ;;
      esac

  script:
    - ./ci/build.sh
    - ./ci/test.sh
    - if [ "$BUILD_TYPE" = "autotools" -a "$DIST" = "DEBIAN" ]; then ./ci/distcheck.sh ; fi
    - if [ "$BUILD_TYPE" = "coverage" ]; then ./ci/covupload.sh ; fi

