# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: NetBSD

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-netbsd
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: NetBSD
    steps:
      - uses: actions/checkout@v4

      - name: Test
        uses: cross-platform-actions/action@v0.24.0
        env:
          DIST: NETBSD
          BUILD_TYPE: "cmake"
          CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=DEBUG -DCARES_STATIC=ON -DCARES_STATIC_PIC=ON -G Ninja"
          CMAKE_TEST_FLAGS: "-DCARES_BUILD_TESTS=ON"
          PKG_PATH: https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/10.0/All/
          TEST_FILTER: "--gtest_filter=-*LiveSearchTXT*:*LiveSearchANY*:*Parallel*"
          TEST_DEBUGGER: "gdb"
        with:
          operating_system: netbsd
          version: '10.0'
          shell: 'bash'
          environment_variables: DIST BUILD_TYPE CMAKE_FLAGS CMAKE_TEST_FLAGS PKG_PATH TEST_FILTER TEST_DEBUGGER
          run: |
            echo "BUILD_TYPE: $BUILD_TYPE"
            echo "CMAKE_FLAGS: $CMAKE_FLAGS"
            echo "CMAKE_TEST_FLAGS: $CMAKE_TEST_FLAGS"
            echo "PKG_PATH: $PKG_PATH"
            sudo -E /usr/pkg/sbin/pkg_add -u bash cmake googletest pkgconf ninja-build gdb
            sudo ln -sf /usr/pkg/bin/bash /bin/bash
            ./ci/build.sh
            ./ci/test.sh

