# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: OpenWatcom
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-openwatcom
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    name: OpenWatcom
    steps:
      - uses: open-watcom/setup-watcom@v0
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: configure
        run: buildconf.bat
        shell: cmd
      - name: Build c-ares
        run: |
          wmake -u -f Makefile.Watcom
      - name: distclean
        run: |
          wmake -u -f Makefile.Watcom clean

